"use client";

import { Geist, Geist_Mono } from "next/font/google";
import { useState } from "react";
import "./globals.css";
import Providers from "./providers";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import MobileMenu from "../components/layout/MobileMenu";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <html lang="en" className={poppins.variable}>
      <body className="min-h-screen flex flex-col font-sans">
        <Providers>
          <Header onMenuToggle={() => setMenuOpen(!menuOpen)} />
            <main>
              {children}
            </main>
          <Footer />
          <MobileMenu open={menuOpen} onClose={() => setMenuOpen(false)} />
        </Providers>
      </body>
    </html>
  );
}
